Repository sattwik21/Python-Practice, pull requests merged in 2021-09, with the labels that each got.

#1 Added Desktop Assistant Project
  Projects/Desktop_asistant/Desktop_Assistant.py
Labels: hacktoberfest-accepted

#2 added new python programs for competitive programing.
  simplecalculator.py
  split_array_program1.py
Labels: hacktoberfest-accepted, approved

#3 decimal to octal converter
  decimal_octal_conv.py
Labels: hacktoberfest-accepted, approved

#5 Create mad libs generator python program
  mad_libs_generator.py
Labels: hacktoberfest-accepted, approved

#7 Binary search python
  Program/Binary_search.py
  Program/binary to hex.py
Labels: hacktoberfest-accepted, approved

#4 basic recursion algorithm
  Program/factorial.py
Labels: hacktoberfest-accepted, approved

#9 Our personal bank, no security just code
  Projects/banking.py
Labels: hacktoberfest-accepted, approved

#10 Image to pencil sketch and plagiarism checker
  Projects/image_2_sketch.py.py
  Projects/plagiarism_checker.py
Labels: hacktoberfest-accepted, approved

#6 Added word and character counter program
  Program/word_counter.py
Labels: hacktoberfest-accepted, approved

#8 Face Recognition using Haarcascades
  Projects/FaceRecognition.ipynb
  Projects/haarcascade_frontalface_default.xml
Labels: good first issue, hacktoberfest-accepted, approved
