Repository sattwik21/Python-Practice, pull requests merged in 2021-10, with the labels that each got.

#11 Python project
  Projects/python turtle graphics.py
Labels: hacktoberfest-accepted, approved

#15 added: number_pattern.py
  Program/number_pattern.py
Labels: hacktoberfest-accepted, approved

#12 Add a Project
  Projects/Text_to_Handwritten_Text.py
Labels: hacktoberfest-accepted, approved

#16 Create password generator.py
  Projects/password generator.py
Labels: hacktoberfest-accepted, approved

#17 added a program to generate random password
  Program/random pass generator.py
Labels: hacktoberfest-accepted, approved

#14 A port scanner in Python
  Program/checkleapyear.py
Labels: hacktoberfest-accepted, approved

#13 countrol mouse project
  Control Mouse/Mouse_Control.py
Labels: hacktoberfest-accepted, approved

#18 Yts Discord Bot
  Projects/Yts Discord Bot/Procfile
  Projects/Yts Discord Bot/commands.txt
  Projects/Yts Discord Bot/requirements.txt
  Projects/Yts Discord Bot/yts.py
Labels: hacktoberfest-accepted, approved

#19 Tic_Tac_Toe_Code
  tic_tac_toe.py
Labels: hacktoberfest-accepted, approved

#20 Tribonacci Numbers in python
  Program/Tribonacci_Numbers.py
Labels: hacktoberfest-accepted, approved

#21 Create armstrong.py
  Program/armstrong.py
Labels: hacktoberfest-accepted, approved

#22 Create palindrome.py
  Program/palindrome.py
Labels: hacktoberfest-accepted, approved

#25 QRCode Generator
  Projects/qr_code_generator/.gitignore
  Projects/qr_code_generator/qr_generator.py
  Projects/qr_code_generator/requirements.txt
Labels: good first issue, hacktoberfest-accepted, approved

#27 Reinforcement Learning project
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/README.md
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/__pycache__/main.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/ai_run.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/highway_run.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/main.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/requirements.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/test.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/training_ckpt/checkpoint
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/training_ckpt/cp.ckpt.data-00000-of-00001
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/training_ckpt/cp.ckpt.index
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/RL_dino/vidw_model.h5
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/README.md
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/__init__.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/__pycache__/__init__.cpython-37.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/__pycache__/__init__.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/envs/__init__.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/envs/__pycache__/__init__.cpython-37.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/envs/__pycache__/__init__.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/envs/__pycache__/enviroment_gym.cpython-37.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/envs/__pycache__/enviroment_gym.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/envs/enviroment_gym.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/game/DINO_game.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/game/__init__.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/game/__pycache__/DINO_game.cpython-37.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/game/__pycache__/DINO_game.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/game/__pycache__/__init__.cpython-37.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/game/__pycache__/__init__.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/utils/__init__.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/utils/__pycache__/__init__.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/utils/__pycache__/chromedriver_installer.cpython-38.pyc
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino/utils/chromedriver_installer.py
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino_game.egg-info/PKG-INFO
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino_game.egg-info/SOURCES.txt
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino_game.egg-info/dependency_links.txt
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino_game.egg-info/requires.txt
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/gym_dino_game.egg-info/top_level.txt
  Projects/Applying Reinforcement Learning to train an agent to play the gym dino game/gym-dino-game/setup.py
Labels: hacktoberfest-accepted, approved

#32 Initial commit
  Projects/acronym_generator.py
Labels: hacktoberfest-accepted, approved

#28 Added Inventory Management System Project in Projects Folder
  Projects/Inventory_Management_System/WARDROBE IMS USING JSON - ADDING NEW ITEMS.ipynb
  Projects/Inventory_Management_System/WARDROBE IMS USING JSON - CREATING SALES.JSON FILE.ipynb
  Projects/Inventory_Management_System/WARDROBE IMS USING JSON - PURCHASING AND PRODUCING THE BILL.ipynb
  Projects/Inventory_Management_System/record.json
  Projects/Inventory_Management_System/sales.json
Labels: hacktoberfest-accepted, approved

#29 Added Intermediate Python Project
  Quiz Game/__pycache__/data.cpython-38.pyc
  Quiz Game/__pycache__/question_model.cpython-38.pyc
  Quiz Game/__pycache__/quiz_brain.cpython-38.pyc
  Quiz Game/data.py
  Quiz Game/main.py
  Quiz Game/question_model.py
  Quiz Game/quiz_brain.py
Labels: hacktoberfest-accepted, approved

#30 gives the N largest element in list 2 approaches
  Program/N_largest_element_in_list.py
Labels: hacktoberfest-accepted

#31 Added Menu based Calculator
  Program/menu_based_calc.py
Labels: hacktoberfest-accepted, approved

#23 Create hash.py
  Program/hash.py
Labels: hacktoberfest-accepted, approved

#34 add keylogger.py
  Program/keylogger.py
Labels: hacktoberfest-accepted, approved

#35 Automating Mail
  Projects/MailingGotEasy/.gitignore
  Projects/MailingGotEasy/db.sqlite3
  Projects/MailingGotEasy/mailing/__init__.py
  Projects/MailingGotEasy/mailing/admin.py
  Projects/MailingGotEasy/mailing/apps.py
  Projects/MailingGotEasy/mailing/migrations/__init__.py
  Projects/MailingGotEasy/mailing/models.py
  Projects/MailingGotEasy/mailing/static/mailing/favicon.ico
  Projects/MailingGotEasy/mailing/templates/mailing/continued.html
  Projects/MailingGotEasy/mailing/templates/mailing/home.html
  Projects/MailingGotEasy/mailing/templates/mailing/pdf0.html
  Projects/MailingGotEasy/mailing/templates/mailing/pdf1.html
  Projects/MailingGotEasy/mailing/templates/mailing/pdf2.html
  Projects/MailingGotEasy/mailing/templates/mailing/pdfv0.html
  Projects/MailingGotEasy/mailing/templates/mailing/pdfv1.html
  Projects/MailingGotEasy/mailing/templates/mailing/pdfv2.html
  Projects/MailingGotEasy/mailing/tests.py
  Projects/MailingGotEasy/mailing/views.py
  Projects/MailingGotEasy/manage.py
  Projects/MailingGotEasy/media/temporary.html
  Projects/MailingGotEasy/requirements.txt
  Projects/MailingGotEasy/sending_mails/__init__.py
  Projects/MailingGotEasy/sending_mails/asgi.py
  Projects/MailingGotEasy/sending_mails/settings.py
  Projects/MailingGotEasy/sending_mails/urls.py
  Projects/MailingGotEasy/sending_mails/wsgi.py
Labels: hacktoberfest-accepted, approved

#37 Web scraping
  Projects/Web scraping/Amazon_reviews.csv
  Projects/Web scraping/Amazon_reviews.ipynb
Labels: hacktoberfest-accepted, approved

#38 Summer Olympics Data Analysis Project added in Projects Folder
  Projects/Summer_Olympics_Data_Analysis/Summer Olympics Data Analysis.ipynb
  Projects/Summer_Olympics_Data_Analysis/Summer Olympics DataSet.csv
Labels: hacktoberfest-accepted, approved

#39 Face Detection Python Script
  Projects/Face_Detection/face_detect_cam.py
  Projects/Face_Detection/haar_face.xml
  Projects/Face_Detection/readme.md
Labels: hacktoberfest-accepted, approved

#41 Added a Project
  Projects/Language Translator/Language_Translator.py
  Projects/Language Translator/Readme.md
  Projects/Language Translator/clicking.png
  Projects/Language Translator/logout.png
  Projects/Language Translator/translater.ico
Labels: hacktoberfest-accepted, approved

#40 Made Body Mass Index
  Projects/bmi.py
Labels: hacktoberfest-accepted, approved

#42 Added calculator tkinter program
  Program/calculator.py
Labels: hacktoberfest-accepted, approved

#103 Create amstrong_no_between_interval.py
  Program/amstrong_no_between_interval.py
Labels: hacktoberfest-accepted, approved

#101 linkedlistRemNode
  Program/linkedListRemNode.py
Labels: hacktoberfest-accepted, approved

#105 Added a tool that helps understanding hamming code
  Program/hamming.py
Labels: hacktoberfest-accepted, approved

#104 networkx-library
  Program/networkx-lib.py
Labels: hacktoberfest-accepted, approved

#102 Create insertBtwNodes.py
  insertBtwNodes.py
Labels: hacktoberfest-accepted, approved

#108 created complex_num.py and km_to_miles.py
  Program/Complex_Num.py
  Program/km_to_miles.py
Labels: hacktoberfest-accepted, approved

#107 Added bubble sort to PYTHON-PRACTICE
  Program/bubble_sort.py
Labels: hacktoberfest-accepted, approved

#109 RockLee444 - Genetic
  Projects/Neuron/Main.py
  Projects/Neuron/README.md
  Projects/Neuron/TrainedNeuron.py
  Projects/Neuron/requirements.txt
Labels: hacktoberfest-accepted, approved

#114 Implementation of Graph in Python
  Program/Implementation_graph.py
Labels: hacktoberfest-accepted, approved

#112 burrows wheeler algorithm
  burrows_wheeler.py
  ohms_law.py
Labels: good first issue, hacktoberfest-accepted, approved

#115 Coronavirus in Python using Turtle Bot
  Program/Coronavirus_python_turtle.py
Labels: approved

#111 Create ModularExp.py
  Program/ModularExp.py
Labels: hacktoberfest-accepted, approved
